[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "synet"
version = "0.0.3"
dependencies = [
    "torch",
    "keras",
    "tensorflow",
    "yolov5",
]

[tool.setuptools.package-data]
synet = ["zoo/**/*.yaml"]

[project.scripts]
synet = "synet.__main__:main"
